This notebook is used to track current goals and activities in the
project. It is not an issue tracker (we use GitHub for that). It is a
place to record current activity, successes and failures and near term
plans. A lab notebook if you like.

For best results edit in Emacs Org mode.

* TODO Demo150-publish-on-success

This will be an extension of Demo140. The goal is to push updated
images to DockerHub (tagged with "dev").

** TODO Push container to Docker Hub

*** DONE Create Docker Hub Organization called "ADTD"

https://hub.docker.com/u/adtd/dashboard/teams/owners/




*** DONE Manually push containers to the new org from the test machine

  - [X] Create a repository for each of the containers
    - [X] web
    - [X] rest
    - [X] integration_test
    - [X] load_test
  - [X] Manually push a "dev" tagged versio of each container
    - [X] web
    - [X] rest
    - [X] integration_test
    - [X] load_test





*** TODO Add a push command to Jenkins when tests pass

* TODO Extract common items from docker-compose files
